Better handle error
youpin-city/youpin-bot pull request #26
Opened 2016-09-28 21:38 UTC by heytitle

Currently, if something goes wrong in files such as `youpin.js`, the server doesn't stop which is difficult to what is actually happening when testing with Facebook Messager.

2016-09-29 02:01 UTC, supasate requested changes

2016-09-29 02:01 UTC, supasate commented on app.js
> +  if(process.env.NODE_ENV != "production"){
Use `!==`.
Add spaces before `(` and after `)`

2016-09-29 02:02 UTC, supasate requested changes

2016-09-29 02:02 UTC, supasate commented on app.js
> +    console.log(`Node app is running on port ${app.get('port')}`);
2 spaces are alright. No need to change.

2016-09-29 09:52 UTC, supasate requested changes

2016-09-29 09:52 UTC, supasate commented on app.js
>      process.exit(1);
I mean `if (process.env.NODE_ENV !== "production") {`.

2016-09-29 09:54 UTC, heytitle commented on app.js
>      process.exit(1);
😢

2016-10-01 16:53 UTC, supasate requested changes

2016-10-01 16:53 UTC, supasate commented on app.js
> +    console.log(`Node app is running on port ${app.get('port')}`);
@heytitle this line is not fixed yet

2016-10-02 04:59 UTC, tvirot commented
LOL, @supasate is becoming a lint bot 😆

2016-10-02 16:25 UTC, supasate approved these changes

2016-10-02 16:25 UTC, merged